config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  root 'products#index'

  namespace :sellers do
    resources :orders, only: %i[edit update], shallow: true
  end

  namespace :buyers do
    resources :orders, only: %i[new create destroy], shallow: true
    resources :feedbacks, only: %i[index new create destroy], shallow: true
  end

  resources :orders, only: %i[index show]

  resources :shopping_carts, only: :show do
    member do
      patch :add_product
      patch :delete_product
    end
  end

  post 'search', action: :search, controller: 'search'
  get '/mail', to: "mails#new"
  post '/send_mail', to: "mails#send_mail"
  get '/about', to: "about#index"
  resources :bank_accounts, only: %i[edit update]
  resources :profiles, only: %i[show edit update]
  get '/sort_by_availability', to: 'products#sort_by_availability'
  resources :products do
    member do
      patch :update_count
      patch :add_subscriber
    end
  end
  get '/:category/products', to: 'products#index'
  resources :categories
  resources :users, only: %i[index show edit destroy] do
    patch :update_salary, on: :member
  end
  post :payment, to: 'payments#payment'
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    if user
      if user.buyer?
        buyer_abilities(user)
      elsif user.seller?
        seller_abilities(user)
      elsif user.director?
        director_abilities(user)
      elsif user.admin?
        admin_abilities
      end
    else
      guest_abilities
    end
  end

  def guest_abilities
    can %i[read sort_by_availability], Product
  end

  def buyer_abilities(buyer)
    guest_abilities
    can :read, [ShoppingCart, Category, Order]
    can %i[add_product delete_product], ShoppingCart, { buyer_id: buyer.id }
    can :create, Order
    can :destroy, Order, { buyer_id: buyer.id }
    can :add_subscriber, Product
  end

  def seller_abilities(_seller)
    guest_abilities
    can :read, [Category, Order]
    can %i[create update destroy], [Product, Category]
    can :update, Order
    can :update_count, Product
  end

  def director_abilities(user)
    seller_abilities(user)
    can %i[update_salary destroy], User
  end

  def admin_abilities
    can :manage, :all
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bank_account.rb
# frozen_string_literal: true

class BankAccount < ApplicationRecord
  belongs_to :buyer

  validates :amount, presence: true
end

app/models/buyer.rb
# frozen_string_literal: true

class Buyer < User
  has_one :shopping_cart, dependent: :destroy
  has_one :bank_account, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :feedbacks
  has_many :products, through: :feedbacks

  after_create :add_shop_cart_and_bank_account

  private

  def add_shop_cart_and_bank_account
    shopping_cart = ShoppingCart.create!(buyer_id: id)
    bank_account = BankAccount.create!(buyer_id: id)
    save
  end
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :products, dependent: :destroy

  has_one_attached :image

  validates :title, :url_name, presence: true
end

app/models/director.rb
# frozen_string_literal: true

class Director < User
end

app/models/feedback.rb
class Feedback < ApplicationRecord
  belongs_to :buyer, class_name: "Buyer"
  belongs_to :product

  validates :body, presence: true
end

app/models/order.rb
# frozen_string_literal: true

class Order < ApplicationRecord
  belongs_to :buyer, class_name: 'Buyer'
  belongs_to :seller, class_name: 'Seller', optional: true
  belongs_to :shopping_cart

  validates :payment_type, :status, presence: true

  scope :created, -> { where(status: 'created') }
  scope :executable, -> { where(status: 'executable') }
  scope :completed, -> { where(status: 'completed') }
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  belongs_to :category
  has_and_belongs_to_many :subscribers, class_name: "Buyer"
  has_many :feedbacks
  has_many :buyers, through: :feedbacks

  has_many_attached :images

  validates :article, :description, :price, presence: true

  def overall_rating
    rating = 0.0
    feedbacks = Feedback.where(product_id: self)
    feedbacks.each do |feedback|
      rating += feedback.score
    end
    return rating.zero? ? rating : rating / feedbacks.count
  end
end

app/models/seller.rb
# frozen_string_literal: true

class Seller < User
  has_many :execute_orders, class_name: 'Order', foreign_key: :seller_id, dependent: :nullify
end

app/models/shopping_cart.rb
# frozen_string_literal: true

class ShoppingCart < ApplicationRecord
  belongs_to :buyer, class_name: 'Buyer', foreign_key: :buyer_id
  has_one :order
  has_many :shopping_cart_products
  has_many :products, through: :shopping_cart_products

  def total_price
    products = shopping_cart_products.eager_load(:product)
    total_price = 0

    products.each do |product|
      total_price += product.product.price * product.count
    end

    total_price
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :validatable

  validates :first_name, :last_name, presence: true

  def buyer?
    is_a?(Buyer)
  end

  def seller?
    is_a?(Seller)
  end

  def director?
    is_a?(Director)
  end

  def creator?(resource)
    resource.buyer.id == id
  end

  def performer?(order)
    order.seller.id == id
  end
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/mails_controller.rb
class MailsController < ApplicationController
  before_action :authenticate_user!

  def new; end

  def send_mail
    message = params[:body]
    user = current_user
    SupportMailer.digest(user, message).deliver_now
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :get_user, only: %i[show edit update_salary destroy]

  def index
    @buyers = Buyer.all.paginate(page: params[:page], per_page: 3)
    @sellers = Seller.all.paginate(page: params[:page], per_page: 3)
  end

  def show
    @completed_orders = @user.execute_orders.where(status: "completed") if @user.seller?
  end

  def update_salary
    @user.salary = user_params[:salary]

    if @user.save
      redirect_to @user
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to users_path
  end

  private

  def user_params
    params.require(:seller).permit(:salary)
  end

  def get_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  AVAILABLE_FLASH = { notice: 'success', alert: 'danger' }.freeze
end

app/helpers/categories_helper.rb
# frozen_string_literal: true

module CategoriesHelper
end

app/helpers/orders_helper.rb
# frozen_string_literal: true

module OrdersHelper
end

app/helpers/payments_helper.rb
# frozen_string_literal: true

module PaymentsHelper
end

app/helpers/products_helper.rb
# frozen_string_literal: true

module ProductsHelper
end

app/helpers/profiles_helper.rb
# frozen_string_literal: true

module ProfilesHelper
end

app/helpers/sellers_helper.rb
# frozen_string_literal: true

module SellersHelper
end

app/views/users/index.html.slim
.sellers
  div class="row"
    div class="col-md-6"
      h3= t('.sellers')
      - @sellers.each do |seller|
        div class="card mb-3 bg-transparent" style="max-width: 540px;"
          div class="card-body"
            h5 class="card-title"= link_to "#{seller.first_name} #{seller.last_name}", user_path(seller), class: 'text-dark text-decoration-none'
            p class="card-text"= t('.seller_id', id: seller.id)
            p class="card-text"= "Количество выполненных заказов: #{seller.execute_orders.where(status: "completed").count}"
        div class="digg_pagination"
          p= will_paginate @sellers
    div class="col-md-6"
      h3= t('.buyers')
      - @buyers.each do |buyer|
        div class="card mb-3 bg-transparent" style="max-width: 540px;"
          div class="card-body"
            h5 class="card-title"= link_to "#{buyer.first_name} #{buyer.last_name}", user_path(buyer), class: 'text-dark text-decoration-none'
            p class="card-text"= t('.buyer_id', id: buyer.id)
        div class="digg_pagination"
          p= will_paginate @buyers

app/views/users/show.html.slim
div class="card mb-3 bg-transparent" style="max-width: 640px;"
  div class="card-body"
    - if @user.seller?
      h5 class="card-title"= t('.seller', first_name: @user.first_name, last_name: @user.last_name)
      p class="card-text"= t('.seller_id', id: @user.id)
      p class="card-text"= "#{t('.salary')}: #{@user.salary}"
      p class="card-text"= "Количество выполненных заказов: #{@completed_orders.count}"
      p class="card-text"
        = form_with(model: @user, url: update_salary_user_path, method: :patch) do |f|
          p
            = f.label :salary, t('.salary')
            = f.number_field :salary
          p
            = f.submit t('.save')
      p class="card-text"= button_to user_path(@user), method: :delete, class: "btn btn-danger" do
        = t('.dismiss')
    - if @user.buyer?
      p class="card-title"= t('.buyer', first_name: @user.first_name, last_name: @user.last_name)
      p class="card-text"= t('.email', email: @user.email)
      p class="card-text"= t('.phone', phone: @user.phone)
      p class="card-text"= t('.delivery_address', address: @user.address)
    p= link_to t('.back'), users_path