config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  root 'products#index'

  namespace :sellers do
    resources :orders, only: %i[edit update], shallow: true
  end

  namespace :buyers do
    resources :orders, only: %i[new create destroy], shallow: true
    resources :feedbacks, only: %i[index new create destroy], shallow: true
  end

  resources :orders, only: %i[index show]

  resources :shopping_carts, only: :show do
    member do
      patch :add_product
      patch :delete_product
    end
  end

  post 'search', action: :search, controller: 'search'
  get '/mail', to: "mails#new"
  post '/send_mail', to: "mails#send_mail"
  get '/about', to: "about#index"
  resources :bank_accounts, only: %i[edit update]
  resources :profiles, only: %i[show edit update]
  get '/sort_by_availability', to: 'products#sort_by_availability'
  resources :products do
    member do
      patch :update_count
      patch :add_subscriber
    end
  end
  get '/:category/products', to: 'products#index'
  resources :categories
  resources :users, only: %i[index show edit destroy] do
    patch :update_salary, on: :member
  end
  post :payment, to: 'payments#payment'
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  belongs_to :category
  has_and_belongs_to_many :subscribers, class_name: "Buyer"
  has_many :feedbacks
  has_many :buyers, through: :feedbacks

  has_many_attached :images

  validates :article, :description, :price, presence: true

  def overall_rating
    rating = 0.0
    feedbacks = Feedback.where(product_id: self)
    feedbacks.each do |feedback|
      rating += feedback.score
    end
    return rating.zero? ? rating : rating / feedbacks.count
  end
end

app/controllers/products_controller.rb
# frozen_string_literal: true

class ProductsController < ApplicationController
  before_action :authenticate_user!, except: :index
  before_action :get_product, only: %i[show new edit update destroy update_count add_subscriber]

  authorize_resource

  def index
    @products = params['category'] ? products_with_category : all_products
  end

  def sort_by_availability
    @products = params['category'] ? products_with_category.where("count > ?", 0) : all_products.where("count > ?", 0)
    render :index
  end

  def show
    @images = @product.images.paginate(page: params[:page], per_page: 1)
    @feedbacks = @product.feedbacks.order(created_at: :desc).paginate(page: params[:page], per_page: 3)
  end

  def new; end

  def edit; end

  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to @product
    else
      render :new
    end
  end

  def update
    if @product.update(product_params)
      redirect_to @product
    else
      render :update
    end
  end

  def destroy
    @product.destroy
    redirect_to products_path
  end

  def update_count
    @product.update(count: @product.count + 1)
    ProductNotifierJob.new.perform(@product) if @product.count == 1
    redirect_to root_path
  end

  def add_subscriber
    @product.subscribers << current_user
    @product.save
    redirect_to root_path
  end

  private

  def product_params
    params.require(:product).permit(
      :title,
      :article,
      :description,
      :price,
      :category_id,
      :brand,
      :model,
      :product_type,
      :color,
      :size,
      :material,
      images: [])
  end

  def get_product
    @product = params[:id] ? Product.with_attached_images.find(params[:id]) : Product.new
  end

  def products_with_category
    Product.joins(:category).where('categories.url_name = ?', params['category']).with_attached_images.paginate(
      page: params[:page], per_page: 3
    )
  end

  def all_products
    Product.with_attached_images.paginate(page: params[:page], per_page: 3)
  end
end

app/helpers/products_helper.rb
# frozen_string_literal: true

module ProductsHelper
end

app/views/products/_product.html.slim
div class="card mb-3 border-primary bg-transparent" style="max-width: 640px;"
  div class="row g-0 align-items-center"
    div class="col-4"
      div class="text-center"
        - if product.images.any?
          = image_tag(product.images[0], size: 120)
        - else
          = t('.empty_image')
    div class="col-8"
      div class="card-body"
        div class="row"
          div class="col-4"
            h5 class="card-title"= link_to "#{product.brand} #{product.model}", product_path(product), class: "text-dark text-decoration-none"
          div class="col-3"
            = product.overall_rating
            = " "
            svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" fill="currentColor" class="bi bi-star" viewBox="0 0 16 16"
              path d="M2.866 14.85c-.078.444.36.791.746.593l4.39-2.256 4.389 2.256c.386.198.824-.149.746-.592l-.83-4.73 3.522-3.356c.33-.314.16-.888-.282-.95l-4.898-.696L8.465.792a.513.513 0 0 0-.927 0L5.354 5.12l-4.898.696c-.441.062-.612.636-.283.95l3.523 3.356-.83 4.73zm4.905-2.767-3.686 1.894.694-3.957a.565.565 0 0 0-.163-.505L1.71 6.745l4.052-.576a.525.525 0 0 0 .393-.288L8 2.223l1.847 3.658a.525.525 0 0 0 .393.288l4.052.575-2.906 2.77a.565.565 0 0 0-.163.506l.694 3.957-3.686-1.894a.503.503 0 0 0-.461 0z"
        p class="card-text"= t('.price', price: product.price)
        p class="card-text"= t('.instock', count: product.count)
        - if current_user&.buyer? && product.count.positive?
          div class="col-4"
            = form_with url: add_product_shopping_cart_path(current_user.shopping_cart), method: :patch do |f|
              p
                = f.label :count, t('.count')
                = f.number_field :count, in: 1..product.count, step: 1, size: "1"
                = f.hidden_field :product_id, value: product.id
              p
                = f.button t('.buy'), class: "btn btn-success"
        - if current_user&.buyer? && product.count.negative? || product.count.zero?
          div class="col-4"= link_to "Сообщить о поступлении", add_subscriber_product_path(product.id), method: :patch
        - if !current_user
          div class="col-4"= link_to t('.buy'), new_user_session_path, method: :get, class: "text-success"
        - if current_user&.seller?
          div class="col-4"= link_to "+", update_count_product_path(product), method: :patch, class: "text-primary"

app/views/products/edit.html.slim
div class="shadow p-3 mb-5 bg-body-tertiary rounded"
  div class="card bg-transparent"
    div class="card-body"
      - if can? :update, @product
        = form_with model: @product do |f|
          p
            = f.label :brand, t('.brand')
            = f.text_field :brand
          p
            = f.label :model, t('.model')
            = f.text_field :model
          p
            = f.label :article, t('.article')
            = f.text_field :article
          p
            = f.label :description, t('.description')
            = f.text_area :description, size: "40x5"
          p
            = f.label :price, t('.price')
            = f.number_field :price
          p
            = f.label :product_type, t('.product_type')
            = f.text_field :product_type
          p
            = f.label :color, t('.color')
            = f.color_field :color
          p
            = f.label :size, t('.size')
            = f.text_field :size
          p
            = f.label :material, t('.material')
            = f.text_field :material
          p
            = f.submit t('.edit')

        p
          = link_to t('.back'), products_path, class: "text-dark text-decoration-none"

app/views/products/index.html.slim
div class="row"
  div class="offset-1"
    p
    table
      thead
        tr
          div class="row"
            div class="col-4"
              h2 class="text-start"= t('.products')
            div class="col-1"
            div class="col-4"
              = form_with url: search_path, class: 'search-form' do |f|
                div class='input-group'
                  = f.text_field "search_data", class: 'form-control'
                  = f.submit 'Search'
            div class="col-3"
      tbody
        tr
          .products
            table class="table"
              tb
                - if can? :create, Product
                  p= link_to t('.add_product'), new_product_path, class: "text-decoration-none"
                - else
                  p= link_to "В наличии", sort_by_availability_path
              tb
                = render @products
            div class="digg_pagination bg-transparent"
              p= will_paginate @products

app/views/products/new.html.slim
div class="card bg-transparent"
  div class="card-body"
    - if can? :create, @product
      = form_with model: @product do |f|
        p
          = f.label :brand, t('.brand')
          = f.text_field :brand
        p
          = f.label :model, t('.model')
          = f.text_field :model
        p
          = f.label :article, t('.article')
          = f.text_field :article
        p
          = f.label :description, t('.description')
          = f.text_area :description, size: "40x5"
        p
          = f.label :price, t('.price')
          = f.number_field :price
        p
          = f.label :product_type, t('.product_type')
          = f.text_field :product_type
        p
          = f.label :color, t('.color')
          = f.color_field :color
        p
          = f.label :size, t('.size')
          = f.text_field :size
        p
          = f.label :material, t('.material')
          = f.text_field :material
        p
          = f.label :images, t('.images')
          = f.file_field :images, multiple: true
        p
          = f.collection_select :category_id, Category.order(:title), :id, :title
        p
          = f.submit t('.create')

      p
        = link_to t('.back'), products_path, class: "text-dark text-decoration-none"

app/views/products/show.html.slim
p
div class="row g-0 align-items-center"
  div class="col-md-4"
    div class="text-center"
      - if @images.any?
        = image_tag(@product.images[0], size: 120)
      - else
        = t('.empty_image')
      div class="digg_pagination"
        p= will_paginate @images
  div class="col-md-7"
    div class="row"
      div class="col-5"
        h5= "#{@product.brand} #{@product.model}"
      div class="col-4"
        = @product.overall_rating
        svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-star" viewBox="0 0 16 16"
          path d="M2.866 14.85c-.078.444.36.791.746.593l4.39-2.256 4.389 2.256c.386.198.824-.149.746-.592l-.83-4.73 3.522-3.356c.33-.314.16-.888-.282-.95l-4.898-.696L8.465.792a.513.513 0 0 0-.927 0L5.354 5.12l-4.898.696c-.441.062-.612.636-.283.95l3.523 3.356-.83 4.73zm4.905-2.767-3.686 1.894.694-3.957a.565.565 0 0 0-.163-.505L1.71 6.745l4.052-.576a.525.525 0 0 0 .393-.288L8 2.223l1.847 3.658a.525.525 0 0 0 .393.288l4.052.575-2.906 2.77a.565.565 0 0 0-.163.506l.694 3.957-3.686-1.894a.503.503 0 0 0-.461 0z"
    p= t('.article', article: @product.article)
    p= t('.description', description: @product.description)
    p= "Тип: #{@product.product_type}"
    p= "Размер: #{@product.size}"
    p= "Материал: #{@product.material}"
    p= t('.price', price: @product.price)
    p= t('.instock', count: @product.count)
    div class="row"
      - if !current_user
        div class="col-6"= button_to t('.buy'), new_user_session_path, method: :get, class: "btn btn-success"
      - if current_user&.buyer?
        - if @product.count.positive?
          div class="col-6"
            = form_with url: add_product_shopping_cart_path(current_user.shopping_cart), method: :patch do |f|
              = f.label :count, t('.count')
              = " "
              = f.number_field :count, in: 1..@product.count, step: 1, size: "1"
              = f.hidden_field :product_id, value: @product.id
              = " "
              = f.button t('.buy'), class: "btn btn-success"
              p
        - if @product.count.negative? || @product.count.zero?
          div class="col-4"= link_to "Сообщить о поступлении", add_subscriber_product_path(@product), method: :patch
          p
      - if current_user&.buyer?
        div class="row"
          div class="col-6"
            button class="btn btn-primary" type="button" data-bs-toggle="collapse" data-bs-target="#collapseFeedback" aria-expanded="false" aria-controls="collapseFeedback"
              = "Оставить отзыв"
            p
            div class="collapse" id="collapseFeedback"
              div class="card card-body"
                = form_with model: current_user.feedbacks.build, url: buyers_feedbacks_path, method: :post do |f|
                  p= f.text_field :body, placeholder: 'Отзыв...'
                  p
                    = f.number_field :score, in: 1..5, step: 1
                    = f.hidden_field :product_id, value: @product.id
                  p= f.submit "Оставить"
      div class="row"
        h6= 'Отзывы о товаре:'
        div class="col-6"
          - if @feedbacks.empty?
            p Нет отзывов
          - else
            - @feedbacks.each do |feedback|
                p
                .feedback
                  div class="card"
                    div class="card-header"
                      div class="row"
                        div class="col-6 text-center"= "#{current_user.first_name} #{current_user.last_name}:"
                        div class="col-2 offset-md-3"
                          = "#{feedback.score}"
                          svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-star" viewBox="0 0 16 16"
                            path d="M2.866 14.85c-.078.444.36.791.746.593l4.39-2.256 4.389 2.256c.386.198.824-.149.746-.592l-.83-4.73 3.522-3.356c.33-.314.16-.888-.282-.95l-4.898-.696L8.465.792a.513.513 0 0 0-.927 0L5.354 5.12l-4.898.696c-.441.062-.612.636-.283.95l3.523 3.356-.83 4.73zm4.905-2.767-3.686 1.894.694-3.957a.565.565 0 0 0-.163-.505L1.71 6.745l4.052-.576a.525.525 0 0 0 .393-.288L8 2.223l1.847 3.658a.525.525 0 0 0 .393.288l4.052.575-2.906 2.77a.565.565 0 0 0-.163.506l.694 3.957-3.686-1.894a.503.503 0 0 0-.461 0z"
                    .feedback-show-link
                      div class="card-body text-truncate"= feedback.body
            div class="digg_pagination"
              p= will_paginate @feedbacks
      - if can? :update, @product
        div class="col-sm-4"= button_to t('.edit'), edit_product_path(@product), class: "btn btn-primary"
      - if can? :destroy, @product
        div class="col-sm-4"= button_to t('.delete'), product_path(@product), method: :delete, class: "btn btn-danger"
      p= link_to t('.back'), products_path, class: "text-dark text-decoration-none"